apiVersion: v1
kind: Service
metadata:
  name: soniq-api
  namespace: soniq
  labels:
    app.kubernetes.io/name: soniq-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: soniq
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: soniq-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
