apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - migrate-job.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - api-pdb.yaml
  - worker-pdb.yaml
