apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: soniq-migrate
  namespace: soniq
  labels:
    app.kubernetes.io/name: soniq-migrate
    app.kubernetes.io/component: migrate
    app.kubernetes.io/part-of: soniq
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: soniq-migrate
      app.kubernetes.io/component: migrate
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 7233
