apiVersion: v1
kind: Service
metadata:
  name: {{ include "soniq.apiName" . }}
  namespace: {{ include "soniq.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "soniq.apiName" . }}
    app.kubernetes.io/component: api
    {{- include "soniq.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "soniq.apiName" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
