apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soniq.configName" . }}
  namespace: {{ include "soniq.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "soniq.fullname" . }}
    {{- include "soniq.commonLabels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
