{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "soniq.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "soniq.fullname" . }}
    {{- include "soniq.commonLabels" . | nindent 4 }}
{{- end }}
