{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soniq.serviceAccountName" . }}
  namespace: {{ include "soniq.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "soniq.fullname" . }}
    {{- include "soniq.commonLabels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
